// AUTO-GENERATED by scripts/seed-cache.ts — do not edit manually
import type { EnrichedData, AgentsResult, GeneratedSite, ProjectResult } from "../types";

import * as ridgelineOutdoor from "./ridgeline-outdoor";
import * as nimbusCloud from "./nimbus-cloud";

export interface CachedPipeline {
  enriched: EnrichedData;
  agents: AgentsResult;
  build: GeneratedSite;
  project: ProjectResult;
}

const CACHE: Record<string, CachedPipeline> = {
  "Ridgeline Outdoor Education": {
    enriched: ridgelineOutdoor.enriched,
    agents: ridgelineOutdoor.agents,
    build: ridgelineOutdoor.build,
    project: {
      filename: "ridgeline-outdoor-education-claude-project-kit.zip",
      downloadedAt: "2026-04-13T15:50:30.000Z",
    },
  },
  "Nimbus Cloud Solutions": {
    enriched: nimbusCloud.enriched,
    agents: nimbusCloud.agents,
    build: nimbusCloud.build,
    project: {
      filename: "nimbus-cloud-solutions-claude-project-kit.zip",
      downloadedAt: "2026-04-13T15:58:12.948Z",
    },
  },
};

export function getCachedPipeline(businessName: string): CachedPipeline | undefined {
  return CACHE[businessName];
}
