// AUTO-GENERATED by scripts/seed-cache.ts — do not edit manually
import type { EnrichedData, AgentsResult, GeneratedSite } from "../types";

export const SESSION_ID = "nimbus-bold";

export const enriched: EnrichedData = {
  "client": {
    "name": "Priya Anand",
    "businessName": "Nimbus Cloud Solutions",
    "email": "priya@nimbuscloud.io",
    "phone": "(415) 600-7742",
    "industry": "B2B SaaS / Cloud Infrastructure",
    "industryCategory": "Technology Services",
    "location": "San Francisco, CA"
  },
  "brand": {
    "tagline": "Infrastructure that scales with ambition.",
    "tone": [
      "confident",
      "technical",
      "forward-thinking",
      "enterprise-grade",
      "authoritative"
    ],
    "voiceGuidelines": "Nimbus Cloud Solutions communicates with technical precision while maintaining approachability for C-suite decision-makers. The voice balances deep cloud expertise with clarity, avoiding unnecessary jargon while demonstrating command of enterprise infrastructure challenges. Confidence stems from proven results, not hyperbole.",
    "colors": {
      "primary": {
        "hex": "#1B3DE8",
        "name": "Nimbus Blue"
      },
      "secondary": {
        "hex": "#E8EFFE",
        "name": "Cloud White"
      }
    }
  },
  "services": [
    {
      "name": "Cloud Migration",
      "description": "Seamlessly transition your legacy infrastructure to modern cloud platforms with zero downtime. Our proven migration methodology includes comprehensive assessment, risk mitigation planning, and phased execution that minimizes business disruption while maximizing cloud ROI.",
      "keywords": [
        "cloud migration services",
        "AWS migration",
        "Azure migration",
        "legacy to cloud",
        "enterprise cloud transition"
      ]
    },
    {
      "name": "DevOps Automation",
      "description": "Accelerate your software delivery pipeline with intelligent automation frameworks. We design and implement CI/CD pipelines, infrastructure as code, and automated testing workflows that reduce deployment times by up to 80% while improving reliability and team velocity.",
      "keywords": [
        "DevOps automation",
        "CI/CD pipeline",
        "infrastructure as code",
        "automated deployments",
        "DevOps consulting"
      ]
    },
    {
      "name": "Kubernetes Management",
      "description": "Harness the full power of container orchestration with expert Kubernetes implementation and management. From cluster design and deployment to ongoing optimization and scaling strategies, we ensure your containerized applications run efficiently at any scale.",
      "keywords": [
        "Kubernetes management",
        "container orchestration",
        "K8s consulting",
        "Kubernetes deployment",
        "microservices architecture"
      ]
    },
    {
      "name": "Security & Compliance",
      "description": "Protect your cloud infrastructure with enterprise-grade security frameworks and compliance automation. We implement zero-trust architectures, conduct vulnerability assessments, and ensure adherence to SOC 2, HIPAA, GDPR, and industry-specific regulatory requirements.",
      "keywords": [
        "cloud security",
        "compliance automation",
        "SOC 2 compliance",
        "cloud security audit",
        "HIPAA cloud compliance"
      ]
    },
    {
      "name": "24/7 Infrastructure Monitoring",
      "description": "Maintain peak performance and reliability with round-the-clock infrastructure monitoring and rapid incident response. Our proactive monitoring systems detect anomalies before they impact users, with dedicated support teams ensuring 99.99% uptime SLAs.",
      "keywords": [
        "24/7 cloud monitoring",
        "infrastructure monitoring",
        "proactive alerting",
        "incident response",
        "uptime management"
      ]
    }
  ],
  "seo": {
    "primaryKeywords": [
      "cloud infrastructure solutions",
      "enterprise cloud migration",
      "DevOps automation services",
      "Kubernetes management",
      "cloud security compliance"
    ],
    "secondaryKeywords": [
      "B2B cloud services San Francisco",
      "AWS migration consulting",
      "cloud infrastructure monitoring",
      "container orchestration services",
      "enterprise DevOps consulting",
      "cloud compliance automation",
      "scalable cloud solutions",
      "managed Kubernetes services"
    ],
    "metaDescription": "Nimbus Cloud Solutions delivers enterprise cloud infrastructure, migration, DevOps automation, and 24/7 monitoring. Scalable solutions for ambitious businesses."
  },
  "businessDetails": {
    "yearsInBusiness": "Established cloud infrastructure provider",
    "serviceArea": "San Francisco Bay Area and nationwide remote services",
    "uniqueSellingPoints": [
      "Zero-downtime cloud migration methodology with proven enterprise track record",
      "24/7 dedicated monitoring and support with 99.99% uptime SLA guarantees",
      "Deep expertise across AWS, Azure, and Google Cloud Platform ecosystems",
      "Security-first approach with built-in compliance for regulated industries",
      "Custom DevOps automation that reduces deployment times by up to 80%"
    ]
  }
} as EnrichedData;

export const agents: AgentsResult = {
  "crm": {
    "clientId": "cli_3847",
    "projectId": "proj_2916",
    "status": "intake_complete",
    "pipeline": "Website · [budget tier not specified]",
    "dealValue": "TBD",
    "createdAt": "2025-01-17T08:45:32Z",
    "contact": {
      "name": "Priya Anand",
      "email": "priya@nimbuscloud.io",
      "phone": "(415) 600-7742",
      "businessName": "Nimbus Cloud Solutions"
    }
  },
  "creative": {
    "brandVoice": {
      "tone": "Confident, technically authoritative, and strategically focused—speaking directly to CTOs, VPs of Engineering, and technical decision-makers who value precision and proven results over marketing fluff.",
      "personality": "Nimbus Cloud Solutions is the trusted technical advisor that enterprise leaders turn to when infrastructure stakes are high. We combine deep cloud expertise with business acumen, speaking the language of both engineering teams and C-suite executives. Our confidence comes from battle-tested methodologies and measurable outcomes, not empty promises.",
      "languageGuidelines": [
        "Lead with outcomes and measurable results (percentages, SLAs, timeframes) rather than generic benefits",
        "Use technical terminology accurately when it adds precision, but always explain implications for business goals",
        "Replace weak modifiers (very, really, quite) with specific data points and concrete examples",
        "Frame challenges as solvable problems with clear methodologies, not obstacles or pain points",
        "Demonstrate expertise through strategic insights rather than listing credentials or certifications",
        "Use active voice and direct statements that convey decisiveness and accountability",
        "Balance forward-thinking vision with proven, implementable solutions available today"
      ]
    },
    "heroSection": {
      "headline": "Infrastructure that scales with ambition.",
      "subheadline": "Enterprise cloud solutions engineered for zero-downtime migration, intelligent automation, and 99.99% uptime. Transform legacy infrastructure into competitive advantage.",
      "ctaText": "Schedule Infrastructure Assessment"
    },
    "pages": [
      {
        "name": "Home",
        "sections": [
          {
            "type": "hero",
            "heading": "Infrastructure that scales with ambition.",
            "content": "When your cloud infrastructure becomes a bottleneck instead of an accelerator, you need more than basic hosting—you need strategic architecture built for scale. Nimbus Cloud Solutions delivers enterprise-grade cloud migration, DevOps automation, and 24/7 monitoring that transforms infrastructure from a cost center into competitive advantage. Our zero-downtime methodologies and security-first approach have helped ambitious companies migrate critical workloads, reduce deployment times by up to 80%, and maintain 99.99% uptime SLAs. Whether you're planning your first cloud migration or optimizing existing infrastructure across AWS, Azure, or Google Cloud Platform, our proven frameworks ensure your technology foundation matches your growth trajectory."
          },
          {
            "type": "features",
            "heading": "Enterprise Cloud Infrastructure, Engineered for Results",
            "content": "From complex cloud migrations to Kubernetes orchestration and comprehensive security compliance, Nimbus delivers the technical depth and strategic planning that enterprise infrastructure demands. Our migration methodology eliminates downtime through phased execution and comprehensive risk mitigation, while our DevOps automation frameworks accelerate software delivery pipelines with intelligent CI/CD implementation and infrastructure as code. We provide expert Kubernetes management that harnesses container orchestration at scale, backed by 24/7 infrastructure monitoring that detects anomalies before they impact users. Security and compliance automation ensures adherence to SOC 2, HIPAA, GDPR, and industry-specific regulatory requirements without sacrificing velocity. Every solution is architected with redundancy, scalability, and performance optimization as foundational principles, not afterthoughts."
          },
          {
            "type": "content",
            "heading": "Why Technical Leaders Choose Nimbus",
            "content": "Infrastructure decisions have cascading implications across engineering velocity, operational costs, security posture, and business continuity. That's why CTOs and VPs of Engineering partner with Nimbus for cloud transformations that cannot afford failure. Our zero-downtime migration methodology has successfully transitioned mission-critical applications for enterprises where even minutes of outage translate to significant revenue impact and customer trust erosion. We architect solutions with deep expertise across AWS, Azure, and Google Cloud Platform ecosystems, ensuring vendor-optimal implementations rather than one-size-fits-all approaches. Our security-first philosophy integrates compliance requirements directly into infrastructure design, transforming regulatory obligations from obstacles into systematic, automated processes. The result is infrastructure that adapts to business needs rather than constraining them—scaling seamlessly during growth, maintaining resilience during incidents, and reducing technical debt while accelerating development cycles."
          },
          {
            "type": "testimonials",
            "heading": "Trusted by Enterprise Teams",
            "content": "Our clients range from Series B startups scaling rapidly to established enterprises modernizing legacy infrastructure. They choose Nimbus because migration and optimization projects require both technical precision and strategic business understanding. Engineering teams appreciate our hands-on expertise and collaborative approach to DevOps automation and Kubernetes implementation. C-suite executives value our clear communication around risk mitigation, cost optimization, and compliance requirements. The common thread is organizations where infrastructure reliability directly impacts revenue, customer experience, or regulatory standing—contexts where expertise, methodology, and accountability matter more than price alone."
          },
          {
            "type": "cta",
            "heading": "Start With a Comprehensive Infrastructure Assessment",
            "content": "Every successful cloud transformation begins with understanding current state architecture, identifying optimization opportunities, and mapping a strategic roadmap aligned with business objectives. Our infrastructure assessment examines your existing environment across security, performance, scalability, and cost efficiency dimensions. We identify migration risks, compliance gaps, and automation opportunities, then deliver a prioritized implementation plan with clear timelines and expected outcomes. This assessment provides the technical foundation for informed decisions about cloud strategy, whether you're planning initial migration or optimizing existing infrastructure. Schedule your assessment to discover how Nimbus methodologies apply to your specific infrastructure challenges and growth goals."
          }
        ],
        "metaTitle": "Nimbus Cloud Solutions | Enterprise Cloud Infrastructure & Migration",
        "metaDescription": "Enterprise cloud migration, DevOps automation & Kubernetes management with 99.99% uptime SLAs. Zero-downtime methodology for AWS, Azure, GCP infrastructure."
      },
      {
        "name": "Services",
        "sections": [
          {
            "type": "hero",
            "heading": "Cloud Infrastructure Solutions Built for Enterprise Scale",
            "content": "Modern cloud infrastructure requires more than migration and management—it demands strategic architecture that anticipates growth, prevents failures, and accelerates business capabilities. Nimbus Cloud Solutions delivers comprehensive services spanning migration, automation, orchestration, security, and monitoring. Our approach integrates these disciplines into cohesive infrastructure strategies rather than treating them as isolated projects, ensuring every component works together to support your business objectives with measurable reliability and performance."
          },
          {
            "type": "content",
            "heading": "Cloud Migration",
            "content": "Seamlessly transition legacy infrastructure to modern cloud platforms with our proven zero-downtime migration methodology. We begin with comprehensive assessment of your existing environment, identifying dependencies, performance baselines, and potential migration risks. Our phased execution approach migrates workloads systematically, validating functionality at each stage while maintaining full production availability. This methodology minimizes business disruption while maximizing cloud ROI through right-sized resource allocation and architecture optimization. Whether moving from on-premises data centers to AWS, Azure, or Google Cloud Platform, our migration frameworks have successfully transitioned mission-critical applications for enterprises where downtime carries significant business impact. Post-migration optimization ensures you leverage cloud-native capabilities for improved performance, reduced costs, and enhanced scalability."
          },
          {
            "type": "content",
            "heading": "DevOps Automation",
            "content": "Accelerate software delivery pipelines with intelligent automation frameworks designed for enterprise velocity and reliability. We implement comprehensive CI/CD pipelines that automate building, testing, and deployment processes, reducing deployment times by up to 80% while improving consistency and reducing human error. Our infrastructure as code implementations using Terraform, CloudFormation, or Azure Resource Manager templates ensure environment consistency and enable rapid scaling. Automated testing workflows integrated directly into deployment pipelines catch issues before production, while monitoring and rollback automation provides safety nets for continuous delivery. These frameworks don't just speed up deployments—they fundamentally transform development team velocity, enabling rapid iteration and experimentation without sacrificing stability or security."
          },
          {
            "type": "content",
            "heading": "Kubernetes Management",
            "content": "Harness the full power of container orchestration with expert Kubernetes implementation and ongoing management. Our Kubernetes solutions span initial cluster design optimized for your workload characteristics, production deployment with high availability and disaster recovery, and ongoing optimization for performance and cost efficiency. We implement microservices architectures that leverage Kubernetes' orchestration capabilities for independent scaling, rapid deployment, and resilient operations. Whether you're containerizing existing applications or architecting new cloud-native systems, our Kubernetes expertise ensures efficient operation at any scale. Ongoing management includes version upgrades, security patching, resource optimization, and troubleshooting—maintaining cluster health while your teams focus on application development rather than infrastructure complexity."
          },
          {
            "type": "content",
            "heading": "Security & Compliance",
            "content": "Protect cloud infrastructure with enterprise-grade security frameworks and compliance automation built for regulated industries. We implement zero-trust security architectures that verify every access request regardless of source, conduct comprehensive vulnerability assessments identifying potential threats before exploitation, and ensure systematic adherence to SOC 2, HIPAA, GDPR, and industry-specific regulatory requirements. Our approach integrates security directly into infrastructure design and DevOps workflows rather than treating it as a separate audit function. Automated compliance monitoring continuously validates security controls and generates audit-ready documentation, transforming regulatory obligations from periodic fire drills into systematic, ongoing processes. This security-first methodology provides the assurance that enterprise customers and auditors demand without creating bottlenecks in development velocity."
          },
          {
            "type": "content",
            "heading": "24/7 Infrastructure Monitoring",
            "content": "Maintain peak performance and reliability with round-the-clock infrastructure monitoring and rapid incident response backed by 99.99% uptime SLAs. Our proactive monitoring systems track performance metrics, resource utilization, and application health across your entire cloud environment, detecting anomalies and potential issues before they impact users. Intelligent alerting escalates genuine incidents to our dedicated support teams while filtering routine fluctuations, ensuring rapid response to actual problems without alert fatigue. When incidents occur, our established runbooks and automated remediation capabilities often resolve issues before manual intervention is required. For complex situations, experienced cloud engineers provide immediate troubleshooting and resolution. This comprehensive monitoring approach transforms infrastructure reliability from hopeful aspiration into contractual commitment, providing the assurance that mission-critical applications demand."
          },
          {
            "type": "cta",
            "heading": "Discuss Your Infrastructure Requirements",
            "content": "Every organization faces unique infrastructure challenges based on application architecture, growth trajectory, regulatory environment, and technical team capabilities. Connect with our cloud infrastructure specialists to discuss how Nimbus services address your specific requirements. We'll explore your current environment, understand your business objectives, and outline a tailored approach that delivers measurable improvements in reliability, performance, security, and cost efficiency."
          }
        ],
        "metaTitle": "Cloud Services: Migration, DevOps, Kubernetes & Security | Nimbus",
        "metaDescription": "Comprehensive cloud services including zero-downtime migration, DevOps automation, Kubernetes management, security compliance, and 24/7 monitoring for enterprises."
      },
      {
        "name": "About",
        "sections": [
          {
            "type": "hero",
            "heading": "Cloud Infrastructure Expertise That Enterprises Depend On",
            "content": "Nimbus Cloud Solutions was founded on a straightforward premise: enterprise cloud infrastructure requires both deep technical expertise and strategic business understanding. Too many cloud providers excel at one while neglecting the other, delivering technically sound solutions that miss business objectives or business-focused strategies that ignore infrastructure realities. We bridge this gap by combining hands-on cloud engineering experience with genuine understanding of how infrastructure decisions impact revenue, customer experience, compliance, and competitive positioning."
          },
          {
            "type": "about",
            "heading": "Our Approach to Cloud Infrastructure",
            "content": "Every infrastructure decision involves tradeoffs between competing priorities—performance versus cost, velocity versus stability, security versus usability, standardization versus flexibility. Our role is helping technical leaders navigate these tradeoffs with clarity rather than prescribing one-size-fits-all solutions. We begin every engagement by understanding business context: growth projections, revenue models, regulatory requirements, team capabilities, and competitive dynamics. This business foundation informs technical recommendations, ensuring infrastructure investments align with strategic priorities. Our methodologies emphasize measured, phased implementations that deliver incremental value rather than risky big-bang transformations. We document decisions, transfer knowledge systematically, and build internal team capabilities rather than creating permanent dependencies. This approach has earned long-term partnerships with clients who view us as extension of their technical leadership rather than external vendors executing isolated projects."
          },
          {
            "type": "content",
            "heading": "Why We Built Nimbus",
            "content": "The cloud infrastructure landscape is crowded with providers offering similar technical capabilities at comparable price points. What differentiates outcomes isn't access to technology—it's how that technology is architected, implemented, and optimized for specific business contexts. We founded Nimbus after repeatedly seeing enterprises struggle with cloud migrations and optimizations despite engaging credentialed consultants and certified partners. The pattern was consistent: technically competent implementations that nonetheless missed business requirements, created operational bottlenecks, or introduced unforeseen costs and complexities. These failures rarely stemmed from insufficient technical knowledge—they resulted from inadequate business understanding and communication gaps between technical teams and executive leadership. Nimbus exists to solve this problem by maintaining fluency in both technical infrastructure and business strategy, translating between engineering realities and business objectives, and delivering solutions that serve both dimensions effectively."
          },
          {
            "type": "content",
            "heading": "Our Commitment to Clients",
            "content": "When enterprises entrust Nimbus with infrastructure migrations and optimizations, they're accepting significant technical risk and business exposure. We honor that trust through systematic methodologies proven across diverse implementations, transparent communication about risks and tradeoffs throughout engagements, contractual SLA commitments backed by monitoring and incident response capabilities, and knowledge transfer that builds internal team capabilities rather than dependencies. Our success metrics extend beyond project completion to long-term infrastructure performance, cost efficiency, team productivity, and business outcome achievement. We measure ourselves by whether infrastructure becomes an accelerator for business ambitions rather than merely a functional requirement. This commitment shapes every technical decision, client interaction, and strategic recommendation."
          },
          {
            "type": "content",
            "heading": "Serving San Francisco and Beyond",
            "content": "Based in San Francisco with deep roots in the Bay Area technology ecosystem, Nimbus serves clients across the nation through remote collaboration frameworks proven effective for distributed infrastructure projects. Our San Francisco location provides proximity to innovative companies pushing cloud architecture boundaries while informing our understanding of emerging patterns, technologies, and methodologies. However, our service delivery model doesn't require geographic proximity—modern collaboration tools, systematic documentation practices, and clear communication protocols enable effective partnerships regardless of location. Whether you're scaling a startup in the Bay Area or modernizing enterprise infrastructure nationally, Nimbus delivers the same rigorous methodology and technical expertise."
          },
          {
            "type": "cta",
            "heading": "Partner With Nimbus for Your Cloud Infrastructure",
            "content": "If you're evaluating cloud migration, seeking DevOps automation expertise, or need strategic guidance for infrastructure optimization, let's discuss how Nimbus methodologies apply to your specific challenges and objectives. Connect with our team to explore partnership opportunities and determine whether our approach aligns with your infrastructure requirements and organizational culture."
          }
        ],
        "metaTitle": "About Nimbus Cloud Solutions | Enterprise Cloud Infrastructure Experts",
        "metaDescription": "San Francisco-based cloud infrastructure specialists delivering enterprise migration, DevOps automation, and security solutions with proven methodologies."
      },
      {
        "name": "Contact",
        "sections": [
          {
            "type": "hero",
            "heading": "Start the Conversation About Your Cloud Infrastructure",
            "content": "Whether you're planning a complex cloud migration, optimizing existing infrastructure, or exploring DevOps automation opportunities, Nimbus Cloud Solutions brings the technical expertise and strategic perspective that enterprise projects demand. Connect with our team to discuss your specific challenges, objectives, and timeline."
          },
          {
            "type": "contact",
            "heading": "Schedule Your Infrastructure Assessment",
            "content": "Every successful cloud transformation begins with comprehensive understanding of your current environment and clear definition of target outcomes. Our infrastructure assessment examines your existing architecture across security, performance, scalability, and cost dimensions, identifying optimization opportunities and migration risks. We deliver a prioritized implementation roadmap with specific recommendations, timeline estimates, and expected business outcomes. This assessment provides the technical foundation for informed infrastructure decisions and strategic planning. To schedule your assessment or discuss your cloud infrastructure requirements, reach Priya Anand directly at priya@nimbuscloud.io or (415) 600-7742. We'll arrange a conversation to understand your context and determine how Nimbus methodologies address your specific needs."
          },
          {
            "type": "content",
            "heading": "What to Expect When You Contact Nimbus",
            "content": "When you reach out to Nimbus, you'll speak directly with cloud infrastructure specialists who understand both technical implementation details and business strategy implications. Our initial conversations focus on understanding your current environment, business objectives, timeline constraints, and specific challenges you're facing. We ask detailed questions about your application architecture, team capabilities, compliance requirements, and growth projections because these factors fundamentally shape infrastructure recommendations. Following this discovery conversation, we can provide preliminary assessment of your needs, outline potential approaches and methodologies, and propose next steps that make sense for your situation. There's no pressure for immediate commitments—we focus on determining whether Nimbus expertise and approach align with your requirements before discussing formal engagements."
          },
          {
            "type": "content",
            "heading": "Our Service Area",
            "content": "Nimbus Cloud Solutions is headquartered in San Francisco, California, serving clients throughout the Bay Area and across the nation through proven remote collaboration frameworks. Our infrastructure services—including cloud migration, DevOps automation, Kubernetes management, security implementation, and 24/7 monitoring—don't require geographic proximity for effective delivery. Modern communication tools, systematic documentation practices, and well-defined processes enable us to partner successfully with distributed teams and remote organizations. Whether your infrastructure resides in San Francisco data centers or distributed across multiple cloud regions nationally, Nimbus delivers consistent methodology and expertise."
          },
          {
            "type": "cta",
            "heading": "Ready to Transform Your Cloud Infrastructure?",
            "content": "Contact Nimbus Cloud Solutions today to schedule your comprehensive infrastructure assessment. Reach Priya Anand at priya@nimbuscloud.io or call (415) 600-7742. Let's discuss how our zero-downtime migration methodology, DevOps automation expertise, and 24/7 monitoring capabilities can transform your infrastructure from constraint into competitive advantage."
          }
        ],
        "metaTitle": "Contact Nimbus Cloud Solutions | Schedule Infrastructure Assessment",
        "metaDescription": "Contact Nimbus for enterprise cloud migration, DevOps automation, and infrastructure consulting. San Francisco-based, serving clients nationwide. (415) 600-7742"
      }
    ],
    "seoStrategy": {
      "primaryKeywords": [
        "enterprise cloud migration",
        "DevOps automation services",
        "Kubernetes management consulting",
        "cloud security compliance",
        "24/7 infrastructure monitoring",
        "zero-downtime cloud migration"
      ],
      "contentThemes": [
        "Cloud migration case studies highlighting zero-downtime methodology and business outcomes",
        "DevOps automation best practices for enterprise CI/CD pipeline optimization",
        "Kubernetes architecture patterns for scalable microservices deployments",
        "Cloud security frameworks for SOC 2, HIPAA, and GDPR compliance",
        "Infrastructure cost optimization strategies for AWS, Azure, and GCP",
        "Cloud monitoring and incident response playbooks for 99.99% uptime",
        "Multi-cloud strategy considerations for enterprise infrastructure decisions",
        "Container orchestration performance tuning and resource optimization",
        "Cloud disaster recovery planning and business continuity strategies",
        "Infrastructure as code implementation guides for Terraform and CloudFormation"
      ]
    },
    "colorRationale": "The Nimbus Blue (#1B3DE8) conveys technical authority and enterprise-grade reliability while standing out in a cloud infrastructure market dominated by washed-out blues and grays. This bold, confident blue signals innovation and forward-thinking technology without appearing playful or consumer-oriented. Paired with Cloud White (#E8EFFE) as the secondary color, the palette maintains clarity and readability essential for technical content while evoking the literal cloud infrastructure that Nimbus manages. The high contrast ensures accessibility and professional presentation across all digital touchpoints, reinforcing the brand's commitment to precision and excellence."
  },
  "design": {
    "colors": [
      {
        "role": "primary",
        "hex": "#1B3DE8",
        "name": "Nimbus Blue",
        "usage": "Primary brand color for headers, CTAs, key UI elements"
      },
      {
        "role": "secondary",
        "hex": "#E8EFFE",
        "name": "Cloud White",
        "usage": "Soft backgrounds, card backgrounds, alternate sections"
      },
      {
        "role": "accent",
        "hex": "#0A1F8F",
        "name": "Deep Sky",
        "usage": "Hover states, active links, emphasis elements"
      },
      {
        "role": "accent-light",
        "hex": "#4D6FF5",
        "name": "Electric Azure",
        "usage": "Interactive elements, icons, subtle highlights"
      },
      {
        "role": "neutral-dark",
        "hex": "#1A1F2E",
        "name": "Midnight Slate",
        "usage": "Primary headings, body text, dark UI elements"
      },
      {
        "role": "neutral",
        "hex": "#4A5568",
        "name": "Storm Gray",
        "usage": "Secondary text, descriptions, muted content"
      },
      {
        "role": "neutral-light",
        "hex": "#E2E8F0",
        "name": "Silver Mist",
        "usage": "Borders, dividers, subtle separators"
      },
      {
        "role": "background",
        "hex": "#FFFFFF",
        "name": "Pure White",
        "usage": "Main page background, card surfaces"
      },
      {
        "role": "success",
        "hex": "#10B981",
        "name": "Cloud Green",
        "usage": "Success states, uptime indicators, positive metrics"
      },
      {
        "role": "warning",
        "hex": "#F59E0B",
        "name": "Alert Amber",
        "usage": "Warning states, important notices"
      }
    ],
    "typography": {
      "headingFont": "Inter",
      "bodyFont": "Inter",
      "headingWeight": "700",
      "bodyWeight": "400",
      "secondaryHeadingWeight": "600",
      "boldWeight": "600"
    },
    "layout": {
      "maxWidth": "1280px",
      "sections": [
        {
          "name": "hero",
          "type": "full-bleed",
          "columns": 1,
          "minHeight": "600px"
        },
        {
          "name": "services",
          "type": "contained",
          "columns": 3,
          "gridLayout": "card-grid"
        },
        {
          "name": "features",
          "type": "split",
          "columns": 2,
          "alternating": true
        },
        {
          "name": "stats",
          "type": "full-bleed",
          "columns": 4,
          "alignment": "center"
        },
        {
          "name": "testimonials",
          "type": "contained",
          "columns": 1,
          "carousel": true
        },
        {
          "name": "cta",
          "type": "full-bleed",
          "columns": 1,
          "alignment": "center"
        }
      ]
    },
    "spacing": {
      "sectionPadding": "80px",
      "sectionPaddingMobile": "48px",
      "componentGap": "32px",
      "cardPadding": "40px",
      "gridGap": "24px",
      "elementSpacing": "16px"
    },
    "borderRadius": {
      "small": "4px",
      "medium": "8px",
      "large": "16px",
      "card": "12px"
    },
    "shadows": {
      "card": "0 4px 6px rgba(27, 61, 232, 0.05), 0 1px 3px rgba(0, 0, 0, 0.08)",
      "cardHover": "0 12px 24px rgba(27, 61, 232, 0.12), 0 4px 8px rgba(0, 0, 0, 0.08)",
      "button": "0 2px 4px rgba(27, 61, 232, 0.2)"
    }
  },
  "assets": {
    "logo": {
      "filename": "demo-logo.svg",
      "dimensions": "400x120",
      "size": "24KB"
    },
    "generated": [
      {
        "filename": "favicon.ico",
        "dimensions": "32x32",
        "purpose": "Browser tab icon"
      },
      {
        "filename": "og-image.png",
        "dimensions": "1200x630",
        "purpose": "Social sharing"
      },
      {
        "filename": "hero-2560.webp",
        "dimensions": "2560x1440",
        "purpose": "Desktop hero"
      },
      {
        "filename": "hero-1280.webp",
        "dimensions": "1280x720",
        "purpose": "Tablet hero"
      },
      {
        "filename": "hero-640.webp",
        "dimensions": "640x360",
        "purpose": "Mobile hero"
      }
    ]
  }
} as unknown as AgentsResult;

export const build: GeneratedSite = {
  "sessionId": "nimbus-bold",
  "pages": [
    {
      "name": "Home",
      "filename": "index.html"
    },
    {
      "name": "Services",
      "filename": "services.html"
    },
    {
      "name": "About",
      "filename": "about.html"
    },
    {
      "name": "Contact",
      "filename": "contact.html"
    }
  ],
  "metadata": {
    "framework": "Static HTML + Tailwind CSS CDN",
    "styling": "Tailwind CSS",
    "pageCount": 4,
    "generatedAt": "2026-04-13T15:58:12.938Z"
  }
} as GeneratedSite;
