// AUTO-GENERATED by scripts/seed-cache.ts — do not edit manually
import type { EnrichedData, AgentsResult, GeneratedSite } from "../types";

export const SESSION_ID = "ridgeline-std";

export const enriched: EnrichedData = {
  "client": {
    "name": "Tom Yazzie",
    "businessName": "Ridgeline Outdoor Education",
    "email": "tom@ridgelineoutdoor.org",
    "phone": "(928) 554-0076",
    "industry": "Outdoor Education & Wilderness Training",
    "industryCategory": "Education & Recreation",
    "location": "Northern Arizona"
  },
  "brand": {
    "tagline": "Go further. Come back changed.",
    "tone": [
      "adventurous",
      "inspiring",
      "grounded",
      "community-focused",
      "transformative"
    ],
    "voiceGuidelines": "Our voice reflects the transformative power of wilderness education with a balance of adventure and safety. We speak to participants as capable individuals ready to challenge themselves while emphasizing community, personal growth, and environmental stewardship. Our tone is confident yet humble, inspiring without being extreme, and always grounded in respect for nature and human potential.",
    "colors": {
      "primary": {
        "hex": "#3B6E45",
        "name": "Forest Green"
      },
      "secondary": {
        "hex": "#F2EAD8",
        "name": "Natural Linen"
      }
    }
  },
  "services": [
    {
      "name": "Wilderness Survival Courses",
      "description": "Comprehensive wilderness survival training that teaches essential skills for thriving in backcountry environments. Our courses cover shelter building, fire making, water purification, navigation, foraging, and emergency preparedness. Participants gain confidence and competence through hands-on practice guided by experienced wilderness educators.",
      "keywords": [
        "wilderness survival training",
        "outdoor survival courses",
        "backcountry skills",
        "primitive skills training",
        "survival education Arizona"
      ]
    },
    {
      "name": "Youth Camps",
      "description": "Transformative multi-day camp experiences designed to build confidence, leadership, and outdoor skills in young people. Our youth programs combine adventure activities, environmental education, and character development in a supportive community setting. Campers develop self-reliance, teamwork, and a lifelong connection to the natural world.",
      "keywords": [
        "outdoor youth camps",
        "wilderness camps for kids",
        "adventure camps Arizona",
        "youth leadership programs",
        "summer outdoor education"
      ]
    },
    {
      "name": "Guided Backpacking",
      "description": "Expert-led backpacking expeditions through stunning wilderness landscapes that emphasize Leave No Trace principles and wilderness appreciation. Our guides provide route planning, safety oversight, and skill instruction while creating space for personal reflection and group bonding. Trips range from beginner-friendly overnights to challenging multi-day treks.",
      "keywords": [
        "guided backpacking trips",
        "wilderness backpacking Arizona",
        "backpacking expeditions",
        "outdoor adventure guides",
        "multi-day hiking trips"
      ]
    },
    {
      "name": "Team Building Retreats",
      "description": "Customized outdoor experiences designed to strengthen organizational culture, improve communication, and develop leadership within teams. Our facilitators use challenge activities, group problem-solving, and wilderness settings to create meaningful growth opportunities. Programs are tailored to your group's specific goals and can accommodate various skill levels.",
      "keywords": [
        "corporate team building outdoors",
        "wilderness team retreats",
        "leadership development programs",
        "outdoor corporate training",
        "team building activities Arizona"
      ]
    },
    {
      "name": "First Aid Certification",
      "description": "Wilderness First Aid and First Responder certification courses that prepare participants to manage medical emergencies in remote settings. Our curriculum combines classroom instruction with realistic scenario-based practice, emphasizing decision-making when professional medical help is hours away. Certifications meet industry standards for outdoor professionals and serious recreationalists.",
      "keywords": [
        "wilderness first aid certification",
        "WFA courses",
        "outdoor emergency training",
        "first responder certification",
        "wilderness medicine Arizona"
      ]
    }
  ],
  "seo": {
    "primaryKeywords": [
      "wilderness education Arizona",
      "outdoor survival courses",
      "wilderness first aid training",
      "guided backpacking trips",
      "youth outdoor camps"
    ],
    "secondaryKeywords": [
      "team building retreats Arizona",
      "wilderness survival training Northern Arizona",
      "outdoor education programs",
      "backcountry skills courses",
      "adventure camps for youth",
      "corporate outdoor retreats",
      "Leave No Trace training",
      "wilderness leadership development"
    ],
    "metaDescription": "Ridgeline Outdoor Education offers wilderness survival courses, guided backpacking, youth camps, and team retreats in Arizona. Go further. Come back changed."
  },
  "businessDetails": {
    "yearsInBusiness": "Established outdoor education provider",
    "serviceArea": "Northern Arizona and surrounding wilderness areas",
    "uniqueSellingPoints": [
      "Experienced wilderness educators with deep knowledge of Arizona's diverse ecosystems",
      "Comprehensive programs from beginner youth camps to advanced wilderness medicine certification",
      "Community-focused approach that emphasizes personal growth and environmental stewardship",
      "Small group sizes ensuring personalized instruction and safe, impactful experiences",
      "Commitment to Leave No Trace principles and sustainable outdoor recreation practices"
    ]
  }
} as EnrichedData;

export const agents: AgentsResult = {
  "crm": {
    "clientId": "cli_8472",
    "projectId": "proj_3819",
    "status": "intake_complete",
    "pipeline": "Website · Standard",
    "dealValue": "$1,500",
    "createdAt": "2025-01-17T14:32:18Z",
    "contact": {
      "name": "Tom Yazzie",
      "email": "tom@ridgelineoutdoor.org",
      "phone": "(928) 554-0076",
      "businessName": "Ridgeline Outdoor Education"
    }
  },
  "creative": {
    "brandVoice": {
      "tone": "Adventurous yet grounded, inspiring without being extreme, and deeply respectful of both nature and human potential",
      "personality": "Ridgeline Outdoor Education speaks with the confidence of experienced wilderness guides who believe in their participants' capabilities. We inspire transformation through challenge while maintaining a humble, safety-conscious approach that honors the power of wild places and the growth that happens when people step outside their comfort zones in supportive community.",
      "languageGuidelines": [
        "Use active, vivid verbs that evoke movement and growth (discover, navigate, build, transform) rather than passive observation",
        "Balance adventure language with safety and preparation—inspire without promoting recklessness",
        "Address participants as capable individuals ready to rise to challenges, not as customers needing entertainment",
        "Ground abstract concepts (leadership, resilience, community) in concrete wilderness experiences and skills",
        "Emphasize 'we' and community over individual achievement when describing program outcomes",
        "Reference specific Arizona landscapes and ecosystems to create sense of place",
        "Maintain humility about our role as facilitators—nature does the teaching, we create the conditions"
      ]
    },
    "heroSection": {
      "headline": "Go further. Come back changed.",
      "subheadline": "Wilderness education programs in Northern Arizona that build essential outdoor skills, forge resilient communities, and create transformative experiences in the backcountry.",
      "ctaText": "Explore Our Programs"
    },
    "pages": [
      {
        "name": "Home",
        "sections": [
          {
            "type": "hero",
            "heading": "Go further. Come back changed.",
            "content": "Ridgeline Outdoor Education guides individuals, youth, and teams through transformative wilderness experiences across Northern Arizona's stunning landscapes. Whether you're learning to build fire without matches, navigating alpine terrain with map and compass, or discovering leadership through group challenge, our expert educators create the conditions for real growth. We believe the wilderness is our greatest teacher, and that every person carries the capacity to thrive in wild places when given proper skills, support, and community."
          },
          {
            "type": "features",
            "heading": "Programs That Transform",
            "content": "Our comprehensive wilderness education offerings serve beginners taking their first overnight trip to outdoor professionals seeking advanced certifications. From multi-day youth camps where young people build confidence alongside campfire skills, to intensive wilderness first aid training that prepares you for backcountry emergencies, each program balances hands-on skill development with personal growth. Our guided backpacking expeditions traverse Arizona's diverse ecosystems while our team building retreats use wilderness challenges to strengthen organizational culture. Small group sizes ensure personalized attention, and our commitment to Leave No Trace principles means every participant learns to tread lightly while going far."
          },
          {
            "type": "about",
            "heading": "Experienced Guides, Proven Methods",
            "content": "Our wilderness educators bring decades of combined backcountry experience and deep knowledge of Arizona's high deserts, ponderosa forests, and mountain ranges. We're not thrill-seekers—we're patient teachers who understand that true outdoor competence comes from practice, reflection, and community support. Every course we lead emphasizes safety-conscious decision making, environmental stewardship, and the development of both technical skills and inner resilience. We've watched countless participants discover capabilities they didn't know they possessed, and we create space for that discovery with thoughtful curriculum design and genuine care for each person's journey."
          },
          {
            "type": "testimonials",
            "heading": "What Participants Say",
            "content": "Our alumni consistently report that Ridgeline programs marked turning points in their lives—not because we manufactured peak experiences, but because we provided authentic challenges in supportive environments. Parents tell us their children return from youth camps more confident and self-reliant. Corporate teams report improved communication months after retreats. Certification students describe feeling truly prepared for wilderness emergencies. These transformations happen when skilled instruction meets wild landscapes and human potential, creating conditions for growth that extend far beyond the trail."
          },
          {
            "type": "cta",
            "heading": "Ready to Begin Your Journey?",
            "content": "Whether you're seeking wilderness skills for your next adventure, looking for a transformative experience for your child, or wanting to strengthen your team through outdoor challenge, Ridgeline has a program designed for your goals. Browse our upcoming courses, reach out with questions, or register today. Northern Arizona's wilderness is waiting, and so is the person you'll become out there."
          }
        ],
        "metaTitle": "Ridgeline Outdoor Education | Wilderness Courses Arizona",
        "metaDescription": "Wilderness survival, guided backpacking, youth camps, and team retreats in Northern Arizona. Expert outdoor education. Go further. Come back changed."
      },
      {
        "name": "Services",
        "sections": [
          {
            "type": "hero",
            "heading": "Wilderness Education for Every Journey",
            "content": "Ridgeline Outdoor Education offers comprehensive programs designed to meet you where you are and take you further. Our courses combine expert instruction, hands-on practice, and the transformative power of Northern Arizona's wilderness to build competence, confidence, and community."
          },
          {
            "type": "content",
            "heading": "Wilderness Survival Courses",
            "content": "Learn to thrive in backcountry environments through comprehensive survival training that covers the essential skills every wilderness traveler should possess. Our courses teach shelter construction using natural materials, fire making in various conditions, water sourcing and purification, navigation with map, compass and natural indicators, wild plant identification and foraging, and emergency preparedness protocols. You'll practice these skills under the guidance of experienced wilderness educators who emphasize understanding principles over memorizing techniques. Whether you're preparing for extended backcountry trips or simply want the confidence that comes from knowing you could handle yourself in remote settings, these courses provide thorough, practical training grounded in respect for nature's power and generosity."
          },
          {
            "type": "content",
            "heading": "Youth Camps",
            "content": "Our multi-day youth camp programs create transformative experiences where young people develop outdoor skills, leadership capabilities, and lasting connections to the natural world. Campers learn practical wilderness techniques while engaging in age-appropriate adventure activities that build confidence through manageable challenges. Our experienced youth educators facilitate group dynamics that emphasize cooperation over competition, creating supportive communities where every participant belongs. Program days balance skill instruction with exploration, reflection with action, and structured activities with unstructured discovery time. We watch campers arrive uncertain and leave empowered, having learned that they're capable of more than they imagined—building shelters, navigating trails, supporting teammates, and finding comfort in wild places."
          },
          {
            "type": "content",
            "heading": "Guided Backpacking Expeditions",
            "content": "Experience Northern Arizona's stunning wilderness landscapes on expert-led backpacking trips designed for various skill levels and aspirations. Our guides handle route planning, permitting, and safety oversight while teaching Leave No Trace principles and backcountry techniques throughout the journey. Expeditions range from accessible overnight trips perfect for those new to backpacking, to challenging multi-day treks through rugged terrain for experienced hikers seeking deeper wilderness immersion. Along the way, you'll learn efficient packing strategies, campsite selection, navigation skills, wilderness cooking, and the rhythms of backcountry travel. These aren't guided tours—they're educational experiences where you develop real competence while exploring some of Arizona's most beautiful wild places in the supportive company of skilled instructors and fellow adventurers."
          },
          {
            "type": "content",
            "heading": "Team Building Retreats",
            "content": "Strengthen your organization through customized outdoor experiences that use wilderness challenges to develop leadership, improve communication, and build cohesive teams. Our facilitators work with you to understand your group's specific goals, then design programs that address those needs through carefully sequenced challenge activities, group problem-solving scenarios, and reflection exercises. The wilderness setting removes participants from familiar office environments and status hierarchies, creating space for authentic interaction and growth. Activities might include navigation challenges requiring trust and clear communication, group initiatives demanding collaborative problem-solving, or backpacking expeditions that build resilience through shared challenge. We accommodate various fitness levels and customize programs for groups from small leadership teams to larger departments, always maintaining our focus on meaningful outcomes over superficial adventure tourism."
          },
          {
            "type": "content",
            "heading": "Wilderness First Aid Certification",
            "content": "Prepare to manage medical emergencies in remote settings where professional help is hours away through our Wilderness First Aid and First Responder certification courses. Our curriculum combines classroom instruction covering wilderness-specific medical protocols with extensive hands-on scenario practice that simulates the challenges of backcountry emergency response. You'll learn patient assessment systems, injury stabilization techniques, environmental emergency management, evacuation decision-making, and communication strategies for remote incidents. Our instructors bring real experience from wilderness settings and create realistic training scenarios that prepare you for the stress and complexity of actual emergencies. These certifications meet industry standards required for outdoor professionals while providing recreational backcountry travelers with skills and confidence that could save lives when trails end and help is distant."
          },
          {
            "type": "cta",
            "heading": "Find Your Program",
            "content": "Each Ridgeline program offers a unique path to wilderness competence and personal growth. Browse our upcoming course dates, reach out with questions about which program fits your goals, or register today to begin your journey. The skills you learn and the person you become are waiting on the trail ahead."
          }
        ],
        "metaTitle": "Wilderness Courses & Outdoor Programs | Ridgeline Education",
        "metaDescription": "Wilderness survival, youth camps, guided backpacking, team retreats, and first aid certification in Arizona. Expert outdoor education programs for all levels."
      },
      {
        "name": "About",
        "sections": [
          {
            "type": "hero",
            "heading": "Teaching Through Wilderness",
            "content": "Ridgeline Outdoor Education was founded on the belief that wilderness experiences, when thoughtfully facilitated, create conditions for profound personal growth and lasting skill development. We're educators who happen to work in stunning outdoor classrooms across Northern Arizona."
          },
          {
            "type": "content",
            "heading": "Our Philosophy",
            "content": "We believe the wilderness itself is the greatest teacher—our role is creating safe, supportive conditions for that teaching to happen. Every Ridgeline program balances challenge with appropriate support, pushing participants beyond comfort zones while maintaining careful attention to physical and emotional safety. We don't manufacture artificial peak experiences or pursue adventure for its own sake. Instead, we design educational progressions where skills build upon each other, where mistakes become learning opportunities, and where the honest work of developing competence creates genuine confidence. Our commitment to small group sizes ensures personalized instruction, and our emphasis on community means participants support each other's growth while developing their own capabilities."
          },
          {
            "type": "content",
            "heading": "Our Approach to Outdoor Education",
            "content": "Ridgeline programs integrate technical skill instruction with character development, environmental stewardship, and community building. When teaching fire-making, we're also teaching patience, observation, and respect for resources. Navigation courses develop decision-making abilities alongside map-reading skills. Youth camps build self-reliance through mastering practical tasks while fostering cooperation through group challenges. This holistic approach recognizes that outdoor competence requires both hard skills and inner qualities like resilience, humility, and situational awareness. We emphasize Leave No Trace principles not as rules to follow but as ethical framework for engaging respectfully with wild places. Our educators model the attitudes and practices we hope to cultivate, demonstrating that wilderness travel at its best combines capability with care."
          },
          {
            "type": "content",
            "heading": "Why Northern Arizona",
            "content": "Northern Arizona's remarkable ecological diversity provides ideal settings for comprehensive wilderness education. Within short distances, we access high desert landscapes, ponderosa pine forests, alpine meadows, and rugged canyon country—each ecosystem offering unique learning opportunities and distinct challenges. Our educators possess deep knowledge of these environments, understanding seasonal variations, water sources, plant communities, and the specific skills required to travel safely through each terrain type. This intimate familiarity with place allows us to select appropriate sites for different programs and skill levels, matching learning objectives with landscape features. We're not adventure tourism operators taking clients to scenic destinations—we're educators using these diverse wild places as living classrooms where every element contributes to the curriculum."
          },
          {
            "type": "content",
            "heading": "Our Commitment",
            "content": "We're committed to providing wilderness education that's accessible, ethical, and genuinely transformative. This means maintaining affordable program pricing, offering scholarships when possible, and designing courses that accommodate varying experience levels. It means conducting all programs with rigorous safety protocols while still allowing for the productive discomfort that enables growth. It means honoring Indigenous peoples' historical and ongoing relationships with these lands through respectful practices and acknowledgment. It means continually improving our curriculum based on participant feedback and current best practices in outdoor education. Most fundamentally, it means believing in every participant's capacity for growth and creating conditions where that growth can unfold naturally through engagement with wilderness, skilled instruction, and supportive community."
          },
          {
            "type": "cta",
            "heading": "Join Our Community",
            "content": "Ridgeline alumni often tell us their time with us marked the beginning of lifelong relationships with wild places and outdoor recreation. We invite you to become part of this community of wilderness-competent, environmentally-conscious individuals who've discovered what they're capable of when challenged and supported in beautiful, demanding landscapes."
          }
        ],
        "metaTitle": "About Ridgeline Outdoor Education | Arizona Wilderness Experts",
        "metaDescription": "Expert wilderness educators offering transformative outdoor programs in Northern Arizona. Learn our philosophy and approach to wilderness education."
      },
      {
        "name": "Contact",
        "sections": [
          {
            "type": "hero",
            "heading": "Let's Plan Your Wilderness Experience",
            "content": "Whether you're ready to register for an upcoming program, have questions about which course fits your goals, or want to discuss custom programming for your group, we're here to help. Reach out today and let's start the conversation about your wilderness education journey."
          },
          {
            "type": "contact",
            "heading": "Get in Touch",
            "content": "Contact Tom Yazzie and the Ridgeline team by phone at (928) 554-0076 or email tom@ridgelineoutdoor.org. We typically respond within 24 hours and are happy to discuss program details, answer questions about prerequisites or preparation, provide information about upcoming course dates, or explore custom program options for youth groups, schools, or organizations. If you're unsure which program is right for you or your group, we'll take time to understand your goals and experience level to recommend the best fit."
          },
          {
            "type": "content",
            "heading": "Program Registration",
            "content": "Ready to register for an upcoming wilderness course, youth camp, or guided expedition? Contact us to check availability for your preferred dates and receive registration materials. We'll provide detailed information about what to expect, what to bring, and how to prepare. For team building retreats and custom programs, we'll schedule a consultation to discuss your group's specific needs, objectives, and logistics before designing a tailored experience."
          },
          {
            "type": "content",
            "heading": "Visit Our Office",
            "content": "Ridgeline Outdoor Education operates throughout Northern Arizona's wilderness areas, with our base in the region's stunning high country. While most of our work happens on the trail, we're available for in-person meetings by appointment to discuss programs, review itineraries, or simply talk about wilderness education over coffee. Reach out to schedule a time to meet, or to learn more about the specific locations where we conduct various programs."
          },
          {
            "type": "content",
            "heading": "Frequently Asked Questions",
            "content": "Common questions we receive include inquiries about experience prerequisites for different courses, physical fitness requirements, what gear is provided versus what participants should bring, scholarship availability, group size limits, and our cancellation policies. We're happy to address these and any other questions you have. No question is too basic—we'd rather you ask before arriving than feel uncertain. Our goal is ensuring every participant shows up prepared and confident about what lies ahead."
          },
          {
            "type": "cta",
            "heading": "Begin Your Journey Today",
            "content": "The trail is calling, and Ridgeline Outdoor Education is ready to guide your wilderness experience. Whether you're taking your first steps into backcountry travel or advancing existing skills, whether you're seeking personal challenge or team development, contact us today. Tom Yazzie: (928) 554-0076 or tom@ridgelineoutdoor.org. Go further. Come back changed."
          }
        ],
        "metaTitle": "Contact Ridgeline Outdoor Education | Arizona Wilderness Courses",
        "metaDescription": "Contact Ridgeline for wilderness education programs in Northern Arizona. Call (928) 554-0076 or email tom@ridgelineoutdoor.org. Registration and inquiries welcome."
      }
    ],
    "seoStrategy": {
      "primaryKeywords": [
        "wilderness education Arizona",
        "outdoor survival courses Northern Arizona",
        "wilderness first aid training",
        "guided backpacking trips Arizona",
        "youth outdoor camps Arizona"
      ],
      "contentThemes": [
        "Wilderness survival skills tutorials and tips specific to Arizona ecosystems",
        "Leave No Trace principles and ethical wilderness travel practices",
        "Youth development through outdoor education and nature connection",
        "Wilderness first aid scenarios and emergency preparedness guides",
        "Northern Arizona trail guides and backcountry destination features",
        "Team building and leadership development through outdoor challenge",
        "Seasonal wilderness skills (winter camping, desert travel, monsoon safety)",
        "Outdoor gear reviews and packing guides for Arizona conditions",
        "Personal transformation stories from wilderness education participants",
        "Environmental stewardship and conservation in outdoor recreation"
      ]
    },
    "colorRationale": "The Forest Green primary color (#3B6E45) directly connects Ridgeline to the ponderosa pine forests and high country landscapes of Northern Arizona where programs take place, evoking growth, resilience, and the natural world while conveying trustworthiness and groundedness essential for wilderness education. The Natural Linen secondary color (#F2EAD8) references sun-bleached desert stone, weathered trail markers, and the warm earth tones of Arizona's backcountry, creating approachable warmth that balances the primary green and ensures readability while maintaining the organic, unpretentious character that defines Ridgeline's educational philosophy."
  },
  "design": {
    "colors": [
      {
        "role": "primary",
        "hex": "#3B6E45",
        "name": "Forest Green",
        "usage": "Primary brand color for headers, navigation, key CTAs, and brand emphasis"
      },
      {
        "role": "secondary",
        "hex": "#F2EAD8",
        "name": "Natural Linen",
        "usage": "Background sections, card backgrounds, alternating content areas"
      },
      {
        "role": "accent",
        "hex": "#D97E3C",
        "name": "Canyon Terracotta",
        "usage": "Buttons, links, highlights, hover states, call-to-action elements"
      },
      {
        "role": "neutral",
        "hex": "#2C3E36",
        "name": "Deep Pine",
        "usage": "Body text, headings, borders, footer background"
      },
      {
        "role": "background",
        "hex": "#FDFCFA",
        "name": "Alpine White",
        "usage": "Primary page background, card surfaces, content containers"
      },
      {
        "role": "accent-light",
        "hex": "#7FA085",
        "name": "Sage Mist",
        "usage": "Subtle backgrounds, icon containers, badges, secondary UI elements"
      },
      {
        "role": "neutral-light",
        "hex": "#8B9A92",
        "name": "Mountain Gray",
        "usage": "Secondary text, captions, borders, dividers"
      }
    ],
    "typography": {
      "headingFont": "Montserrat",
      "bodyFont": "Open Sans",
      "headingWeight": "600",
      "bodyWeight": "400"
    },
    "layout": {
      "maxWidth": "1280px",
      "sections": [
        {
          "name": "hero",
          "type": "full-bleed",
          "columns": 1
        },
        {
          "name": "services",
          "type": "grid",
          "columns": 3
        },
        {
          "name": "about",
          "type": "split",
          "columns": 2
        },
        {
          "name": "testimonials",
          "type": "contained",
          "columns": 1
        },
        {
          "name": "call-to-action",
          "type": "full-bleed",
          "columns": 1
        },
        {
          "name": "contact",
          "type": "split",
          "columns": 2
        }
      ]
    },
    "spacing": {
      "sectionPadding": "80px",
      "componentGap": "32px"
    }
  },
  "assets": {
    "logo": {
      "filename": "demo-logo.svg",
      "dimensions": "400x120",
      "size": "24KB"
    },
    "generated": [
      {
        "filename": "favicon.ico",
        "dimensions": "32x32",
        "purpose": "Browser tab icon"
      },
      {
        "filename": "og-image.png",
        "dimensions": "1200x630",
        "purpose": "Social sharing"
      },
      {
        "filename": "hero-2560.webp",
        "dimensions": "2560x1440",
        "purpose": "Desktop hero"
      },
      {
        "filename": "hero-1280.webp",
        "dimensions": "1280x720",
        "purpose": "Tablet hero"
      },
      {
        "filename": "hero-640.webp",
        "dimensions": "640x360",
        "purpose": "Mobile hero"
      }
    ]
  }
} as unknown as AgentsResult;

export const build: GeneratedSite = {
  "sessionId": "ridgeline-std",
  "pages": [
    {
      "name": "Home",
      "filename": "index.html"
    },
    {
      "name": "Services",
      "filename": "services.html"
    },
    {
      "name": "About",
      "filename": "about.html"
    },
    {
      "name": "Contact",
      "filename": "contact.html"
    }
  ],
  "metadata": {
    "framework": "Static HTML + Tailwind CSS CDN",
    "styling": "Tailwind CSS",
    "pageCount": 4,
    "generatedAt": "2026-04-13T15:50:30.631Z"
  }
} as GeneratedSite;
