import { writeFileSync, mkdirSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SERVER_CACHE = path.join(__dirname, "..", "server", "cache");
const FALLBACK_FILE = path.join(
  __dirname,
  "..",
  "client",
  "lib",
  "fallback-data.ts"
);

const SERVER = "http://localhost:3001";

const DEMO_INTAKE = {
  businessName: "Lone Star Pet Grooming",
  ownerName: "Maria Santos",
  email: "maria@demo.frasierdigital.com",
  phone: "(281) 555-0142",
  industry: "Pet services",
  services: "Dog grooming, cat grooming, nail trimming, flea treatment",
  brandColors: { primary: "#2D5F2D", secondary: "#F5E6D3" },
  tagline: "Where every pet leaves happy",
  tone: "Friendly, warm, trustworthy",
  pagesNeeded: ["Home", "Services", "About", "Contact"],
  desiredDomain: "lonestarpetgrooming.com",
  budgetTier: "Standard ($1,500)",
  logoUrl: "/demo-logo.svg",
  heroImageUrl: "/demo-hero.jpg",
};

async function post(path: string, body: unknown) {
  const res = await fetch(`${SERVER}${path}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  if (!res.ok) throw new Error(`${path} failed: ${res.statusText}`);
  return res.json();
}

async function main() {
  console.log("Seeding cache — make sure Express server is running on :3001\n");

  mkdirSync(SERVER_CACHE, { recursive: true });

  // Stage 1: Enrich
  console.log("1/4 Enriching intake data...");
  const enriched = await post("/enrich", DEMO_INTAKE);
  writeFileSync(
    path.join(SERVER_CACHE, "enrich.json"),
    JSON.stringify(enriched, null, 2)
  );
  console.log("    ✓ Enrichment cached");

  // Stage 2: Agents
  console.log("2/4 Running agents...");
  const agents = await post("/agents", enriched);
  writeFileSync(
    path.join(SERVER_CACHE, "agents.json"),
    JSON.stringify(agents, null, 2)
  );
  console.log("    ✓ Agents cached");

  // Stage 3: Project (display mode)
  console.log("3/4 Creating project payload...");
  const project = await post("/project", {
    enriched,
    creative: agents.creative,
    mode: "display",
  });
  writeFileSync(
    path.join(SERVER_CACHE, "project.json"),
    JSON.stringify(project, null, 2)
  );
  console.log("    ✓ Project cached");

  // Stage 4: Build
  console.log("4/4 Generating website...");
  const build = await post("/build", {
    enriched,
    creative: agents.creative,
    design: agents.design,
  });
  writeFileSync(
    path.join(SERVER_CACHE, "build.json"),
    JSON.stringify(build, null, 2)
  );
  console.log("    ✓ Build cached");

  // Write fallback-data.ts
  console.log("\nWriting client/lib/fallback-data.ts...");
  const fallbackTs = `// AUTO-GENERATED by scripts/seed-cache.ts — do not edit manually
import type {
  EnrichedData,
  AgentsResult,
  GeneratedSite,
  ProjectResult,
} from "./types";

export const fallbackEnriched: EnrichedData = ${JSON.stringify(enriched, null, 2)} as EnrichedData;

export const fallbackAgents: AgentsResult = ${JSON.stringify(agents, null, 2)} as AgentsResult;

export const fallbackProject: ProjectResult = ${JSON.stringify(project, null, 2)} as ProjectResult;

export const fallbackBuild: GeneratedSite = ${JSON.stringify(build, null, 2)} as GeneratedSite;
`;
  writeFileSync(FALLBACK_FILE, fallbackTs);
  console.log("    ✓ fallback-data.ts written");

  console.log("\n✓ Cache seeding complete!");
  console.log("  Server cache: server/cache/");
  console.log("  Client fallback: client/lib/fallback-data.ts");
}

main().catch((err) => {
  console.error("Cache seeding failed:", err.message);
  process.exit(1);
});
