import type { IntakeData } from "./types";

export const DEMO_COMPANIES: IntakeData[] = [
  {
    businessName: "Blue Mesa Roofing",
    ownerName: "Carlos Mendez",
    email: "carlos@bluemesaroofing.com",
    phone: "(505) 332-0187",
    industry: "Home services / Construction",
    services:
      "Roof replacement, storm damage repair, gutters, inspections, insurance claims assistance",
    brandColors: { primary: "#8B2500", secondary: "#D4C5A9" },
    tagline: "Built tough. Done right.",
    tone: "Reliable, no-nonsense, straightforward",
    pagesNeeded: ["Home", "Services", "About", "Contact"],
    desiredDomain: "bluemesaroofing.com",
    budgetTier: "Starter ($750)",
    logoUrl: "/logos/blue-mesa-roofing.svg",
    designStyle: "standard",
    heroImageUrl: "/demo-hero.jpg",
  },
  {
    businessName: "Petal & Stem Floral Studio",
    ownerName: "Nora Callahan",
    email: "nora@petalandstem.co",
    phone: "(503) 218-4455",
    industry: "Floral design / Events",
    services:
      "Wedding florals, event arrangements, weekly subscriptions, sympathy flowers, workshops",
    brandColors: { primary: "#C2547A", secondary: "#F7F0E6" },
    tagline: "Flowers that tell your story.",
    tone: "Elegant, warm, creative, personal",
    pagesNeeded: ["Home", "Services", "Gallery", "About", "Contact"],
    desiredDomain: "petalandstem.co",
    budgetTier: "Standard ($1,500)",
    logoUrl: "/logos/petal-and-stem.svg",
    designStyle: "standard",
    heroImageUrl: "/demo-hero.jpg",
  },
  {
    businessName: "Harborlight Therapy Group",
    ownerName: "Dr. Sandra Osei",
    email: "sandra@harborlighttherapy.com",
    phone: "(617) 880-3321",
    industry: "Mental health / Wellness",
    services:
      "Individual therapy, couples counseling, anxiety & depression treatment, EMDR, telehealth",
    brandColors: { primary: "#2E6E8E", secondary: "#E8F4F0" },
    tagline: "A steady light through uncertain waters.",
    tone: "Calm, compassionate, professional, reassuring",
    pagesNeeded: ["Home", "Services", "About", "Contact"],
    desiredDomain: "harborlighttherapy.com",
    budgetTier: "Standard ($1,500)",
    logoUrl: "/logos/harborlight-therapy.svg",
    designStyle: "standard",
    heroImageUrl: "/demo-hero.jpg",
  },
  {
    businessName: "Dusty Axle Vintage Motors",
    ownerName: "Ray Kowalski",
    email: "ray@dustyaxle.com",
    phone: "(316) 774-0093",
    industry: "Automotive / Classic cars",
    services:
      "Classic car restoration, engine rebuilds, custom paint, parts sourcing, consignment sales",
    brandColors: { primary: "#1A1A1A", secondary: "#C8922A" },
    tagline: "Bringing legends back to life.",
    tone: "Gritty, passionate, authentic, old-school cool",
    pagesNeeded: ["Home", "Services", "Gallery", "About", "Contact"],
    desiredDomain: "dustyaxle.com",
    budgetTier: "Starter ($750)",
    logoUrl: "/logos/dusty-axle.svg",
    designStyle: "bold",
    heroImageUrl: "/demo-hero.jpg",
  },
  {
    businessName: "Nimbus Cloud Solutions",
    ownerName: "Priya Anand",
    email: "priya@nimbuscloud.io",
    phone: "(415) 600-7742",
    industry: "B2B SaaS / Cloud infrastructure",
    services:
      "Cloud migration, DevOps automation, Kubernetes management, security compliance, 24/7 monitoring",
    brandColors: { primary: "#1B3DE8", secondary: "#E8EFFE" },
    tagline: "Infrastructure that scales with ambition.",
    tone: "Confident, technical, forward-thinking, enterprise-grade",
    pagesNeeded: ["Home", "Services", "About", "Blog", "Contact"],
    desiredDomain: "nimbuscloud.io",
    budgetTier: "Premium ($3,500)",
    logoUrl: "/logos/nimbus-cloud.svg",
    designStyle: "bold",
    heroImageUrl: "/demo-hero.jpg",
  },
  {
    businessName: "The Sourdough Collective",
    ownerName: "James Whitfield",
    email: "james@sourdoughcollective.com",
    phone: "(720) 391-5567",
    industry: "Artisan food / Bakery",
    services:
      "Artisan sourdough loaves, pastries, baking classes, wholesale to restaurants, custom orders",
    brandColors: { primary: "#8C6239", secondary: "#FDF6EC" },
    tagline: "Slow bread. Real food.",
    tone: "Earthy, honest, community-driven, artisanal",
    pagesNeeded: ["Home", "Services", "About", "Contact"],
    desiredDomain: "sourdoughcollective.com",
    budgetTier: "Starter ($750)",
    logoUrl: "/logos/sourdough-collective.svg",
    designStyle: "standard",
    heroImageUrl: "/demo-hero.jpg",
  },
  {
    businessName: "Vantage Point Real Estate",
    ownerName: "Michelle Tran",
    email: "michelle@vantagepointrealty.com",
    phone: "(214) 952-1130",
    industry: "Real estate",
    services:
      "Luxury home sales, buyer representation, investment properties, relocation services, market analysis",
    brandColors: { primary: "#1C3140", secondary: "#C9A84C" },
    tagline: "See further. Live better.",
    tone: "Sophisticated, trustworthy, aspirational, polished",
    pagesNeeded: ["Home", "Services", "About", "Blog", "Contact"],
    desiredDomain: "vantagepointrealty.com",
    budgetTier: "Premium ($3,500)",
    logoUrl: "/logos/vantage-point.svg",
    designStyle: "bold",
    heroImageUrl: "/demo-hero.jpg",
  },
  {
    businessName: "Lone Star Pet Grooming",
    ownerName: "Maria Santos",
    email: "maria@lonestarpetgrooming.com",
    phone: "(281) 555-0142",
    industry: "Pet services / Grooming",
    services:
      "Dog grooming, cat grooming, nail trimming, flea treatment, teeth cleaning",
    brandColors: { primary: "#2D5F2D", secondary: "#F5E6D3" },
    tagline: "Where every pet leaves happy.",
    tone: "Friendly, warm, trustworthy, neighborly",
    pagesNeeded: ["Home", "Services", "About", "Contact"],
    desiredDomain: "lonestarpetgrooming.com",
    budgetTier: "Standard ($1,500)",
    logoUrl: "/logos/lone-star-pet-grooming.svg",
    designStyle: "standard",
    heroImageUrl: "/demo-hero.jpg",
  },
  {
    businessName: "Luma Skincare Lab",
    ownerName: "Aisha Fontaine",
    email: "aisha@lumaskincare.com",
    phone: "(323) 710-4489",
    industry: "Beauty / Skincare e-commerce",
    services:
      "Clean ingredient serums, moisturizers, SPF, personalized skincare consultations, subscription boxes",
    brandColors: { primary: "#D4A8C7", secondary: "#FAFAF5" },
    tagline: "Science-backed. Skin-obsessed.",
    tone: "Clean, modern, confident, inclusive, science-forward",
    pagesNeeded: ["Home", "Services", "About", "Blog", "Contact"],
    desiredDomain: "lumaskincare.com",
    budgetTier: "Premium ($3,500)",
    logoUrl: "/logos/luma-skincare.svg",
    designStyle: "bold",
    heroImageUrl: "/demo-hero.jpg",
  },
  {
    businessName: "Ridgeline Outdoor Education",
    ownerName: "Tom Yazzie",
    email: "tom@ridgelineoutdoor.org",
    phone: "(928) 554-0076",
    industry: "Education / Outdoor recreation",
    services:
      "Wilderness survival courses, youth camps, guided backpacking, team building retreats, first aid certification",
    brandColors: { primary: "#3B6E45", secondary: "#F2EAD8" },
    tagline: "Go further. Come back changed.",
    tone: "Adventurous, inspiring, grounded, community-focused",
    pagesNeeded: ["Home", "Services", "Gallery", "About", "Contact"],
    desiredDomain: "ridgelineoutdoor.org",
    budgetTier: "Standard ($1,500)",
    logoUrl: "/logos/ridgeline-outdoor.svg",
    designStyle: "standard",
    heroImageUrl: "/demo-hero.jpg",
  },
];
